apiVersion: v1
kind: Service 
metadata:
    name: go-demo-8
spec:
    type: NodePort
    ports: 
     - targetPort: 8080
       port: 8080
       nodePort: 30009
    selector: 
           app: go-demo-8           