---
apiVersion: v1
kind: Service
metadata:
  namespace: istio-demo
  name: version1
  labels:
    app: v1
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: v1
---
apiVersion: v1
kind: Service
metadata:
  namespace: istio-demo
  name: version2
  labels:
    app: v2
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: v2