apiVersion: v1
kind: Service 
metadata:
    name: istio-demo-v1
spec: 
    type: ClusterIP
    ports:
     - targetPort: 80
       port: 80
    selector: 
       app: istio-demo-v1
       version: '1'