apiVersion: apps/v1
kind: Deployment          
metadata: 
  name: nginx-deployment
  labels: 
    app: sample
spec:
  template:
    metadata:
      name: nginx
      labels:                      
        app: sample        
    spec:
      containers:
        - name: nginx-deployment
          image: nginx
  replicas: 3
  selector: 
    matchLabels:
        app: sample